Fixed read value bigger than `0x7f` via `BufferedInputStream`
scala-native/scala-native pull request #1922
Opened 2020-10-07 01:22 UTC by catap

`read()` should return a value between `-1` and `255` and `-1` means `EOF`.

When `buf(pos)` contains value bigger than `0x75` for example `171.toByte` and makes `.toInt`, it converts this value to `-85` that can be regarded by enduser as `EOF` if he uses `< 0` condition.

Unfortunately this bug hasn't got workaround on user side because when stream contains `0xff`, the `read()` returns `-1` and it is impossibly to distinguish the `EOF` and `0xff`.

2020-10-07 08:27 UTC, sjrd requested changes
LGTM, other than the formatting issue.

2020-10-07 08:27 UTC, sjrd commented on unit-tests/src/test/scala/java/io/BufferedInputStreamSuite.scala
> +    val in = new BufferedInputStream(arrayIn)
This is not correctly formatted according to scalafmt.

2020-10-07 10:05 UTC, sjrd approved these changes

2020-10-07 13:50 UTC, merged

2020-10-07 20:26 UTC, LeeTibbert commented
This has already been merged which is good.

@catap I should point out pending PRs #1624 & #1623.  They deal with
I believe the exact same issue in DataInputStream and readLine().  You
may end up encountering the same problem  they fix.

2020-10-07 21:19 UTC, ekrich commented
I was hoping that https://github.com/scala-native/scala-native/issues/1918 might be fixed by this but it isn't. Maybe a stream is reading passed the end of a buffer.

@LeeTibbert I don't think your fixes would hurt either.

2020-12-10 19:31 UTC, catap commented
I was wrong. It is possibly to overstep this issue on `0.4.0-M2`.

The workaround:
```scala
class ScalaNativeFriendlyBufferedInputStream(in: InputStream) extends BufferedInputStream(in) {
  private val singleByte = new Array[Byte](1)

  override def read(): Int = synchronized {
    val r = read(singleByte)
    if (r < 0) r
    else singleByte(0).toInt & 0xff
  }
}
```