Fix #1944 - private method annotated with Before crashes compiler
scala-native/scala-native pull request #1958
Opened 2020-10-20 19:19 UTC by WojciechMazur

Resolves #1944 

This PR fixes problem with compiler crashing in the `inject-junit` phase when the method annotated with `Before` is declared with a `private` modifier. The problem did not occur with other access modifiers.  

Although this change fixes the issue it also makes it less compatible with [JUnit API](https://junit.org/junit4/javadoc/latest/org/junit/Before.html) which states:
_Annotating a **public void** method with @Before causes that method to be run before the Test method_
Even though I would opt-in merging this PR as it's not breaking, but it's widening the JUnit features set.

2020-10-20 21:46 UTC, ekrich commented
Yes, after looking at the JUnit API documentation it says that the `@Before` method should be public although I used protected and it worked - I was thinking in Java. Maybe a better idea is to produce a compile error if the method is not public. Is that possible?

https://junit.org/junit4/javadoc/4.12/org/junit/Before.html

I suppose this would apply to `@After`, `@BeforeClass` and `@AfterClass` as well. They all should be public.

2020-10-21 08:03 UTC, WojciechMazur commented
> Maybe a better idea is to produce a compile error if the method is not public. Is that possible?

Yeah, that's possible, although the JUnit inject phase is quite generic in terms of annotated methods, and it would be applied to all of them, it might not be a problem since all of mentioned by you annotations should also be public

2020-10-21 11:13 UTC, WojciechMazur commented
I've applied changes after @ekrich suggestion.
CI failed in source checks and in resolving dependency, rerunning these tests should give us green light.

2020-10-21 14:44 UTC, ekrich commented
One of the last commit in the `java.io` tests included changing all the methods to public that had annotations in anticipation of this fix.

2020-10-22 10:46 UTC, sjrd requested changes

2020-10-22 10:46 UTC, sjrd commented on junit-plugin/src/main/scala/scala/scalanative/junit/plugin/ScalaNativeJUnitPlugin.scala
> +        val nonPublicCalls = calls.filterNot(_.symbol.isPublic)
Doing this after having created all the `calls` means that we're still temporarily generating invalid code. I suggest `partition`ing the `annotatedMethods` according to whether they are public first. Then report errors on the non-public ones, and only generate `mkMethodCall`s for the public ones.

2020-10-22 11:43 UTC, sjrd approved these changes

2020-10-22 16:36 UTC, merged