Port ju.ConcurrentLinkedQueue from Scala.js
scala-native/scala-native pull request #1994
Opened 2020-11-12 09:09 UTC by lolgab

2020-11-12 09:29 UTC, sjrd approved these changes

2020-11-13 09:47 UTC, lolgab commented
This is failing on 2.11 because of the default methods in traits invoked by AbstractCollectionTest etc.
Since there is already a WIP PR for default methods on Scala 2.11 I will wait for it and then rebase this.

2020-11-17 17:17 UTC, LeeTibbert commented
Status:  I created separate PRs for CollectionTest, AbstractCollectionTest, & IterableTest and 
             re-ported the code being tested. TrivialImmutableCollectionTest is part of the CollectionTest PR,
             where the former is first used.  This gives a more defined audit trail to my JavaDefaultMethod
             changes.

             I believe those files can be deleted from this PR as soon as the PRs for the moved tests
             are merged.  The PR (#1997) which had originally holding this PR up has been merged.  

            Thank you for giving me permission to  use/move those Tests.  Saved time, effort, & mistakes.
             
              That leaves the  ConcurrentLinkedQueue.scala & ConcurrentLinkedQueueTest.scala.

2020-11-30 17:28 UTC, LeeTibbert commented
@lolgab   Now that PR #2013 has been merged, I believe that this PR will build on Scala 2.11
after the conflicting files have been removed & the PR re-based.

Thank you for your understanding & patience while I did some of the JavaDefaultMethod work
and for allowing your port in the PR to be used in the default method PRs.

If there is any difficulty with this PR rebuilding, please let me know.  I expect none, but do
not want you spending time cleaning up after my mistakes.

2020-11-30 19:21 UTC, lolgab commented
Wow, the CI is really fast now!

2020-11-30 19:23 UTC, lolgab commented
I rebased after your changes without problems @LeeTibbert 
After merging of this one I will check again for other missing parts we need for ZIO support. Hopefully we can get everything we need before the release.

2020-11-30 21:03 UTC, lolgab commented
@sjrd Ready for another review round

2020-12-01 09:19 UTC, sjrd requested changes
Just one detail.

2020-12-01 09:19 UTC, sjrd commented on javalib/src/main/scala/java/util/concurrent/ConcurrentLinkedQueue.scala
> +  private var _size: Double = 0
In Native we should use a `Long` here instead.

2020-12-01 09:19 UTC, sjrd commented on javalib/src/main/scala/java/util/concurrent/ConcurrentLinkedQueue.scala
> +    _size.toInt
If `_size` is a Long, this will have to be
```scala
if (_size > Int.MaxValue) Int.MaxValue else _size.toInt
```

2020-12-01 14:47 UTC, sjrd approved these changes

2020-12-01 15:42 UTC, merged