Support `java.util.Data` Instant dependent methods
scala-native/scala-native pull request #2088
Opened 2020-12-23 12:32 UTC by WojciechMazur

This PR adds methods added in Java8 to `java.util.Date` that is method `toInstant` and `Date.from(_: Instant)`
It should be rebased on top of merged #2079 as it contains bootstrap of `testsExt` project.

2020-12-29 17:06 UTC, ekrich commented
You have a typo in the title - should be `java.util.Date`.

2021-01-04 09:49 UTC, sjrd requested changes
This should be accompanied by a port of [`InstantTest`](https://github.com/scala-js/scala-js/blob/master/test-suite-ex/shared/src/test/scala/org/scalajs/testsuite/javalib/time/InstantTest.scala) in the unit-test-ext. This is important to make sure that relying on the `ArithmeticException` is indeed correct.

Otherwise, LGTM. (Probably shouldn't be Draft anymore.)

2021-01-04 09:52 UTC, WojciechMazur commented
`InstantTest` was ported in #2087, when it's merged I'll rebase this branch on top of it and convert from draft.

2021-01-07 17:14 UTC, sjrd approved these changes

2021-01-07 17:15 UTC, merged