Remove explicit versions for items in .g8 template.
scala-native/scala-native pull request #2129
Opened 2021-01-23 19:22 UTC by LeeTibbert

We remove the explicit mention of software versions which are
generated by the .g8.  

The .g8 template is the This Single Point of Truth. This eliminates the possibility of version skew due
to double bookkeeping yet preserves the usefulness and intent of that section of documentation.

2021-01-23 19:28 UTC, LeeTibbert commented
@bjornregnell   

If you have time for another cup of coffee, could you review this PR? 
If you can not, I understand. Anyway, thank you.

Folks,
I think I captured my intent of removing software versions.  I always
struggle with English, which is probably why I became a Software Enginner
rather than a famous author.  I welcome suggestions for improvement,
especially in the areas of instructional and International English.

2021-01-23 23:27 UTC, bjornregnell requested changes
@LeeTibbert The text reads fine. My only worry is that it is not easy to find a concrete example of how it should look like. I suggest to link to the actual template files, as beginners might not be familiar with gitter8 and what that is all about...

So good if we could help people create a minimal setup from scratch.

*My suggestion is to include the links in the text instead of just the file names:*
  * [project/plugins.sbt](https://github.com/scala-native/scala-native.g8/blob/master/src/main/g8/project/plugins.sbt)
  * [project/build.properties](https://github.com/scala-native/scala-native.g8/blob/master/src/main/g8/project/build.properties)
  * [build.sbt](https://github.com/scala-native/scala-native.g8/blob/master/src/main/g8/build.sbt)

2021-01-23 23:27 UTC, bjornregnell commented
@LeeTibbert The text reads fine. My only worry is that it is not easy to fins a concrete example of how it should look like. I suggest to link to the actual template files, as beginners might not be familiar with gitter8 and what that is all about...

So good if we could help people create a minimal setup from scratch.

*My suggestion is to include something like:*
If you want to create a minimal setup yourself from scratch, create these files with latest versions as seen in the links below:
  * [project/plugins.sbt](https://github.com/scala-native/scala-native.g8/blob/master/src/main/g8/project/plugins.sbt)
  * [project/build.properties](https://github.com/scala-native/scala-native.g8/blob/master/src/main/g8/project/build.properties)
  * [build.sbt](https://github.com/scala-native/scala-native.g8/blob/master/src/main/g8/build.sbt)

2021-01-23 23:28 UTC, bjornregnell commented
> would you consider my adding you as a co-author in the commit message?

Yes that's fine; thanks for credit!

2021-01-23 23:30 UTC, bjornregnell requested changes
Or simply keep the text you have but just add the links to the actual files in the .g8 template if you like that better...

2021-01-24 04:08 UTC, LeeTibbert commented
Excellent and spot-on suggestions. I will take a run at implementing them in my next activity cycle.
Thank you.

2021-01-24 21:04 UTC, ekrich commented
@LeeTibbert I am not sure where you were talking about options but I think removing the `nativeLinkStubs` is fine. I do think that having logging may be a better choice as an extra setting as people can see the compile/link commands.
```Scala
// (Info is default) Set to Debug to see compile/link commands
logLevel := Level.Info
```

2021-01-26 23:35 UTC, LeeTibbert commented
@bjornregnell I took a run at implementing your suggestion. What do you think?

I think/hope I captured your intent.  Feel free to suggest changes to wording.
There is a reason that I am a developer and not a doc writer: That group
would not let me in...

I think there is a tiny, nano-scale issue with a missing period/full_stop after
 the `main.scala` code block. Lack_of/broken parallelism. I am hoping
no one notices. A period there looked just pain odd. 

Thank you for any review you may have time/interest to give.

Should I be sending coffee beans to Sweden?

2021-01-26 23:39 UTC, LeeTibbert commented
@ekrich Thank you for your reply. Based on feedback from you and others,
I will fall back and take another run at buffing up the .g8 template.  I wanted
to get this PR settled, to release swap space in my brain/guilt_list.

After this PR settles, I hope to do another which will add a brief intermediate
section, assuming more knowledge, describing how to the ` portable-scala /
sbt-crossproject.g8` to create a project sub-sets of JVM, Scala.js, Scala Native.

2021-01-27 09:11 UTC, bjornregnell approved these changes
@LeeTibbert @ekrich This looks fine! I'm sure this will help newcomers!
I have some additional minor tweaks to language etc to suggest (including fixing punctuation and adding explanation of where the out-file is) but I can fix that later this week when I get time to fork it. (And I guess I cannot add stuff to this PR anyway so better get it merged as soon as possible so people can enjoy the new clarity :1st_place_medal:  
So LGTM and I'll try to provide my first commit to make minor improvements in a coming PR as soon as I get some coffee-time off (or rather tea-time as I'm trying to stay away of all this coffee :)).

2021-01-27 09:19 UTC, bjornregnell commented
BTW. I put `logLevel := Level.Info` in `build.sbt` as suggested by @ekrich when I tried it out on my Ubuntu box, but I couldn't tell any difference...  

I got a nice error message the first time I tried to run that clang was missing and a helpful link to were to find info about how to install it so that was a nice newcomer user-experience !

2021-01-27 09:28 UTC, sjrd commented
> BTW. I put `logLevel := Level.Info` in `build.sbt` as suggested by @ekrich when I tried it out on my Ubuntu box, but I couldn't tell any difference in the output from sbt, so I guess this does not help until there are some linking problems?

`logLevel := Level.Info` is the default in sbt.

2021-01-27 09:33 UTC, bjornregnell commented
Aha @sjrd ; yes didn't read @ekrich comment careful enough. Just updated my comment above; I didn't really understand what use I can have of all the debug info I got, but I'm not a C programmer...
```
[debug] Running
[debug] /usr/bin/clang++
[debug] 	-rdynamic
[debug] 	-o
[debug] 	/home/bjornr/tmp/test-scala-native/hello/target/scala-2.13/hello-out
[debug] 	-Wno-override-module
[debug] 	/home/bjornr/tmp/test-scala-native/hello/target/scala-2.13/native/native-code-posixlib_native0.4_2.13-0.4.0-1/scala-native/errno.c.o
[debug] 	/home/bjornr/tmp/test-scala-native/hello/target/scala-2.13/native/native-code-posixlib_native0.4_2.13-0.4.0-1/scala-native/sys/select.c.o
[debug] 	/home/bjornr/tmp/test-scala-native/hello/target/scala-2.13/native/native-code-posixlib_native0.4_2.13-0.4.0-1/scala-native/sys/socket_conversions.c.o
[debug] 	/home/bjornr/tmp/test-scala-native/hello/target/scala-2.13/native/native-code-posixlib_native0.4_2.13-0.4.0-1/scala-native/sys/socket.c.o

```
etc in a lot of lines...

```

2021-01-27 09:37 UTC, bjornregnell commented
So the bottom line is that the current docs and the .g8 template worked like charm for me, even if I don't now much about how to build and link native stuff, so seems rather noob proof :)

2021-01-27 16:15 UTC, ekrich commented
There was a comment to change to debug to see compiling details.

On Wed, Jan 27, 2021 at 1:20 AM Bjorn Regnell <notifications@github.com>
wrote:

> BTW. I put logLevel := Level.Info in build.sbt as suggested by @ekrich
> <https://github.com/ekrich> when I tried it out on my Ubuntu box, but I
> couldn't tell any difference...
>
> I got a nice error message the first time I tried to run that clang was
> missing and a helpful link to were to find info about how to install it so
> that was a nice newcomer user-experience !
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/scala-native/scala-native/pull/2129#issuecomment-768150102>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAHDZQV4KWTCJGWPZWVMMOTS37LE7ANCNFSM4WP5DANQ>
> .
>

2021-01-27 17:10 UTC, ekrich commented
@bjornregnell I am glad you found the error messages helpful. We just worked on the clang detection and enhanced the messages.

2021-01-27 17:16 UTC, bjornregnell commented
As soon as this is merged I will contribute some extra minor tweaks in a new PR, but better get this out as soon as possible to bump version of plugin from milestone to release.

2021-01-27 18:40 UTC, LeeTibbert commented
@bjornregnell Thank you for the re-review and your positive comments.

Yes, another iteration of `sbt.rst` after this PR is merged would be good.
Especially from an instructional professional with a fresh set of eyes.

At some point in the dance, I would like to add a section on 
intermediate .g8 template for projects which support JVM, Scala.js,
and Native.  The name of the existing template is something like
sbt-crossproject-mumble.g8 (sorry for my poor memory)

I would also like to add a pointer to the section in the main
Scala (JVM) documentation  which does a better/alternate
job of describing the use of a .g8 template.  I just came
across that page today (and of course, do not have
the URL at the tip of my fingers, sorry.)

So, please do not wait for me. I suggest that you go first
and I will wait for your PR.  I wanted to write down 
some thoughts of direction, so that others could 
comment and you and I could co-ordinate & take
turns.

IMO, Doc is never perfect, especially as new groups of users are
added. However, it can evolve and approach perfection, where
perfection. like Enlightenment lasts only a moment ;-)  Not
that I have experienced either of those.

2021-01-27 19:03 UTC, bjornregnell commented
@LeeTibbert That's indeed fine with me. I just closed #2122 in favour of this PR. Happy for this one to get merged to open for subsequent tweaks, as you suggest.

2021-02-22 09:47 UTC, WojciechMazur approved these changes

2021-02-22 11:41 UTC, merged