Introduced NativeThread
scala-native/scala-native pull request #2182
Opened 2021-02-26 21:29 UTC by catap

This commit introduced `NativeThread` which is a part of #947

This is a step to split https://github.com/catap/scala-native/tree/multithreading

Co-authored-by: R.Coudert <remi.coudert@epfl.ch>

2021-02-26 22:12 UTC, catap commented
@sjrd / @WojciechMazur can I ask you to review it?

2021-02-27 14:44 UTC, densh approved these changes
LGTM!

2021-03-02 21:51 UTC, WojciechMazur commented
Can't we implement this using Scala Native? We already have bindings for `pthread` and `sched`. All structures are passed by reference so there should be no problem with this.

2021-03-09 02:45 UTC, ekrich requested changes
Everything else looks good but I am not a `pthread` expert so I can't comment on how it works.

2021-03-09 02:45 UTC, ekrich commented on posixlib/src/main/resources/scala-native/nativethread.c
> +int get_max_priority() {
For helper methods. the standard is to prefix the function or define with `scalanative_`. Unfortunately, this was just documented and has not made it in the latest docs yet.
See commit: https://github.com/scala-native/scala-native/pull/2159/commits/4f5859a64e2d5dbcd9b5ade5ab2fd6525552c24a

2021-03-09 02:58 UTC, ekrich commented
@catap or @densh, now that I am looking at this can't these additional functions and helpers just be added to `posix/pthread.scala` and `pthread.c`?

2021-03-09 03:00 UTC, ekrich commented on posixlib/src/main/resources/scala-native/nativethread.c
> +int get_max_priority() {
@WojciechMazur Is it easy enough to publish the latest? I am wondering if a link somewhere pointing to the latest might be good for contributors and people that are curious?

2023-04-12 18:51 UTC, WojciechMazur commented
Thank for your contribution, however we have end up with a different implementation of native thread in current main branch

2023-04-12 18:51 UTC, closed without merging

2023-04-12 20:30 UTC, catap commented
np, thanks!