Install clang-format 6.0
scala-native/scala-native pull request #2240
Opened 2021-04-02 00:46 UTC by ekrich

2021-04-05 09:57 UTC, catap approved these changes
LGTM

2021-04-06 08:54 UTC, WojciechMazur approved these changes

2021-04-06 09:01 UTC, WojciechMazur requested changes

2021-04-06 09:01 UTC, WojciechMazur commented on .github/workflows/check-lint.yml
> +          sudo apt install clang-format-6.0
I've read that GitHub actions provide password-less `sudo` so it should work, however, I have never used it before. Did you have the opportunity to test is before in some other Github Actions CI?

2021-04-06 17:22 UTC, ekrich commented on .github/workflows/check-lint.yml
> +          sudo apt install clang-format-6.0
I have not tried without sudo - it works now - let me check to logs. My guess it that it checks if it is running in a tty and suppresses interaction if not. Do you want me to try without sudo?

2021-04-06 17:24 UTC, ekrich commented on .github/workflows/check-lint.yml
> +          sudo apt install clang-format-6.0
According to the docs `sudo` is needed. https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners

2021-04-06 17:29 UTC, ekrich commented on .github/workflows/check-lint.yml
> +          sudo apt install clang-format-6.0
I actually don't see `-y` as an option for `apt`. It is an option for `apt-get`. http://manpages.ubuntu.com/manpages/trusty/en/man8/apt.8.html

2021-04-06 17:30 UTC, ekrich commented on .github/workflows/check-lint.yml
> +          sudo apt install clang-format-6.0
I guess it seem fine as is - https://github.com/scala-native/scala-native/runs/2250741974

2021-04-07 15:49 UTC, ekrich commented on .github/workflows/check-lint.yml
> +          sudo apt install clang-format-6.0
@WojciechMazur I think this is correct as is based on the docs.

2021-04-08 10:28 UTC, WojciechMazur approved these changes

2021-04-08 10:29 UTC, merged