Implement `java.nio` on Windows
scala-native/scala-native pull request #2358
Opened 2021-09-02 16:30 UTC by WojciechMazur

This PR adds Windows implementation for all `java.nio` methods supported on Unix. 

Scope of changes: 
* Implement WindowsFileSysytem, its provider and Views
* Implement WindowsPath and it's parser
* Conditionally select FS providers using linktime condition
* Adjust some of the java.nio test to be JVM compliment. 
* Added windowslib bindings used by java.nio

2021-09-02 17:17 UTC, ekrich commented on javalib/src/main/scala/scala/scalanative/nio/fs/FileHelpers.scala
> +      val searchPath = path + raw"\*"
Can you use triple quotes for this?

2021-09-02 17:37 UTC, ekrich reviewed
Is there any preference/guidance or alignment with Scala.js when using Java classes?
It seems there are the package alias `ju.Map, jl.Boolean` and the class alias `JMap, JBoolean` strategies.

2021-09-03 09:18 UTC, WojciechMazur commented
> Is there any preference/guidance or alignment with Scala.js when using Java classes?
> It seems there are the package alias `ju.Map, jl.Boolean` and the class alias `JMap, JBoolean` strategies.

@ekrich 
I don't think there is any recommended approach. Even in Scala.js you can find both types of aliases.

2021-09-03 09:19 UTC, WojciechMazur commented on javalib/src/main/scala/scala/scalanative/nio/fs/FileHelpers.scala
> +      val searchPath = path + raw"\*"
Sure, done

2021-09-03 14:02 UTC, sjrd requested changes

2021-09-03 14:02 UTC, sjrd commented on unit-tests/shared/src/test/scala/javalib/nio/file/UnixPathTest.scala
> +  def checkIsUnix() {
Same here: `assumeIsUnix`.

Also, perhaps this can be an `@BeforeClass` in the companion object instead.

2021-09-03 14:02 UTC, sjrd commented on unit-tests/jvm/src/test/resources/BlacklistedTests.txt
> +#scala/javalib/nio/file/UnixPathTest.scala
Why the `#`? Was that intentional?

2021-09-06 09:46 UTC, sjrd approved these changes

2021-09-06 14:50 UTC, merged