Allow to use `java.util.zip` in Windows
scala-native/scala-native pull request #2361
Opened 2021-09-06 16:28 UTC by WojciechMazur

2021-09-13 11:35 UTC, sjrd requested changes

2021-09-13 11:35 UTC, sjrd commented on nativelib/src/main/scala/scala/scalanative/runtime/zlib.scala
> +  sealed trait z_stream
The same issues exist with `gz_header`.

2021-09-14 11:56 UTC, WojciechMazur commented on nativelib/src/main/scala/scala/scalanative/runtime/zlib.scala
> +  sealed trait z_stream
I've removed the `sealed trait z_stream` the only reason for the usage of phantom was to increase type safety, however it's not really helping us with anything. 
Now we define 
```
type z_streamp = Ptr[z_stream[_, _]]
...
private[scalanative] type z_stream[UINT, ULONG] = CStruct14[...]

object z_stream {
def size: CSize = ???
} 
``` 
Is such naming fine or should I rename generic `z_stream[_,_]` to something else, eg. `z_stream_impl[_,_]`

2021-09-17 13:38 UTC, sjrd approved these changes

2021-09-17 13:49 UTC, merged