add fenv.h
scala-native/scala-native pull request #2591
Opened 2022-03-13 03:44 UTC by i10416

close #2590

2022-03-13 03:59 UTC, i10416 commented
Sorry, ready for review now.

2022-03-13 07:52 UTC, i10416 commented
> To use this function, you must turn off floating-point optimizations that could prevent access by using the #pragma fenv_access(on) directive prior to the call.

2022-03-13 07:53 UTC, i10416 commented
https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/fetestexcept1?view=msvc-170

2022-03-13 08:53 UTC, i10416 commented
🤔

2022-03-13 14:05 UTC, i10416 commented
How to use `#pragma` in scala native...?

2022-03-13 14:15 UTC, WojciechMazur commented
> 


> How to use `#pragma` in scala native...?

It's not possible in Scala sources compiled with Scala Native. You can only use it  C/C++ sources

2022-03-13 14:57 UTC, i10416 commented
> It's not possible in Scala sources compiled with Scala Native. 

Oh... the linked Microsoft documentation says that `fenv_access` is __off by default__ and developers need to explicitly set `#pragma fenv_access(on)` to avoid unintended optimization gotcha.

> What directive you wanted to use

I am not going to use any `#pragma` for now, but it is likely that someone who tries to call functions in `fenv.h` on Windows get confused, especially when they can use these functions but functions return unexpected response.

> Maybe there is a workaround for that

Yeah, if there is, I'm sure we need to mention that in scaladoc.

2022-03-13 15:04 UTC, i10416 commented
It seems `feraiseexcept` is not always supported...😖

2022-03-13 18:33 UTC, i10416 commented
Hmmm, some platform/arch add FE_INEXACT flag when FE_OVERFLOW is set.

2022-03-13 18:40 UTC, i10416 commented
I hope `if (fenv.FE_ALL_EXCEPT == 0) {` can be evaluated at compile time and compiler removes clause containing `feraiseexcept` ...

2022-03-13 19:23 UTC, WojciechMazur commented
If it happens only in Windows (CI suggests that), we can replace this test with `if(scalanative.meta.LinktimeInfo.isWindows)` in that case the untaken branch would be dead-code eliminated when linking the NIR, and though we would get rid of undefined symbols reported by LLVM linker. It would then use a mechanism of linktime-values which were used to handle Windows support

2022-03-15 04:15 UTC, i10416 commented
Perhaps fenv tests affect other test results?

2022-03-15 05:55 UTC, i10416 commented on clib/src/main/scala/scala/scalanative/libc/fenv.scala
> +  @name("scalanative_fenv_fe_divbyzero")
Removed fenv.

2022-03-15 16:22 UTC, ekrich requested changes

2022-03-15 16:28 UTC, i10416 commented on clib/src/main/resources/scala-native/fenv.c
> +int scalanative_fenv_fe_divbyzero() { return FE_DIVBYZERO; }
Probably you see older version?

https://github.com/scala-native/scala-native/pull/2591/files#diff-9e88de73f7e02009f1cb7df744326b7d32b1842ff706b2efc505f6471c9ed9bd

2022-03-15 16:30 UTC, i10416 commented on clib/src/main/resources/scala-native/fenv.c
> +int scalanative_fenv_fe_divbyzero() { return FE_DIVBYZERO; }
https://github.com/scala-native/scala-native/pull/2591/commits/b8de2eceecb47c29373e9cb940c61f8e71080443

2022-03-15 16:30 UTC, ekrich commented on clib/src/main/resources/scala-native/fenv.c
> +int scalanative_fenv_fe_divbyzero() { return FE_DIVBYZERO; }
Oh sorry about that.

2022-03-15 16:31 UTC, i10416 commented on clib/src/main/resources/scala-native/fenv.c
> +int scalanative_fenv_fe_divbyzero() { return FE_DIVBYZERO; }
No worries

2022-03-15 16:31 UTC, i10416 commented on clib/src/main/resources/scala-native/fenv.c
> +int scalanative_fenv_fe_divbyzero() { return FE_DIVBYZERO; }
Thank you for reviewing :)

2022-03-16 21:15 UTC, WojciechMazur approved these changes

2022-03-16 21:16 UTC, merged

2023-01-19 03:55 UTC, LeeTibbert commented
@i10416 

I realize that this PR merged almost a year ago.  First, as a member of the SN community, thank you for the PR.

Once upon a time, Scala Native and its tests ran on the FreeBSD operating system.  FreeBSD was never part
of the Continuous Integration (CI) matrix, so failures to run on FreeBSD crept in over time as code was added.


I am trying to get the SN unit-tests running cleanly on FreeBSD again and have a question.
Thought I would contact you, the original author  to ask your help/thoughts.

1) The file is called `FenvTest.scala` but the class is called `FEnvTest` (note the 'E', not 'e').  I noticed this
     when trying to run the class based on the file name.  May I change one name to the other, so both
     match.  Should I change the class to match the file name?  

Thank you for your recommendation.

I would normally not bother the author of a long since merged PR for such a small issue.
I am in that file trying to figure out if a particular feMumble symbol is missing on both FreeBSD X86_64
and arm or only arm architecture.