Add `j.u.c.Flow`
scala-native/scala-native pull request #3099
Opened 2023-01-20 14:42 UTC by armanbilge

- https://docs.oracle.com/javase/9/docs/api/java/util/concurrent/Flow.html
- https://github.com/scala-js/scala-js/pull/4792

2023-01-20 18:08 UTC, LeeTibbert commented
Arman,

Firstly, thank you for getting this done.  Another penny in the jar (sic!).

Do you mind if I do a follow on PR to add a line such as (example, data is incorrect for this PR): 
`// Ported from Scala.js, commit: 0383e9f, dated: 2021-03-07`

to the top of each file?    I find it incredibly helpful when I am faced
with making edits to a file which appears to originally have come from
scala.js if I know  first that it did indeed come from scala.js and
then when the species diverged.  That is, trying to figure
out if the bug at hand has been fixed or obviated in scala.js.

Yes, this is a classic issue of does on spend time at the beginning
to head off a probably greater cost at in a future which may never
come.  I am offering to do the change because I do not
want to make porting from scala.js have so many hoops that
it never gets done.

Thanks,

Lee

2023-01-20 18:17 UTC, armanbilge commented
Thanks for the reminder! I normally add the comment, but won't be able to until the Scala.js PR finalizes and merges.

2023-01-21 00:51 UTC, ekrich requested changes
Just the dates, and since it made it through Scala.js then it is good to go.

2023-01-21 00:54 UTC, ekrich commented on javalib/src/main/scala/java/util/concurrent/Flow.scala
> +// Ported from Scala.js commit: fb20d6f dated: 20 Jan 2023
```suggestion
// Ported from Scala.js commit: fb20d6f dated: 2023-01-20
```
ISO 8601 format is preferable.

2023-01-21 00:54 UTC, ekrich commented on unit-tests/shared/src/test/require-jdk9/org/scalanative/testsuite/javalib/util/concurrent/FlowTest.scala
> +// Ported from Scala.js commit: fb20d6f dated: 20 Jan 2023
```suggestion
// Ported from Scala.js commit: fb20d6f dated: 2023-01-20
```
Ditto.

2023-01-21 01:03 UTC, ekrich commented
That is cool. Never seen `[ci skip]` before.

2023-01-21 01:05 UTC, ekrich approved these changes
Looks good to me.

2023-01-21 12:53 UTC, LeeTibbert commented
If "[ci skip]" does what it appears to do, it will save me _mucho_ time chasing intermittent
build failures on doc-only (.rst, .md) changes.  Thank you.

Arman, thank you for listening to & addressing my concern.

2023-01-25 15:08 UTC, WojciechMazur approved these changes

2023-01-25 15:09 UTC, merged