Add `pledge` and `unveil`
scala-native/scala-native pull request #3823
Opened 2024-03-09 13:39 UTC by catap

`pledge` is using to restrict system operations, and `unveil` to unveil parts of a restricted filesystem view.

Both of them available at OpenBSD for years. Anyway some work to port it to Linux is onging but it far from the end, and the best status is Justine's work to port it into cosmopolitan libc.

2024-03-09 22:11 UTC, WojciechMazur requested changes

2024-03-09 22:11 UTC, WojciechMazur commented on posixlib/src/main/resources/scala-native/unistd.c
> +int pledge(const char *promises, const char *execpromises) {
We should not try to redefine it here under the original name, instead let's define it as `scalanative_pledge` and redirect Scala to it by adding `@name("scalanative_pledge")` annotation. Same for `unveil` function

2024-03-10 09:30 UTC, catap commented
After some thinking I'd like to remove C-level placeholder. Let linker fail if user tries to use this function on unsupported OS.

This is much better and user friendly behaviour that return undocummented error via errno.

I'll update PR shortly

2024-03-10 11:44 UTC, WojciechMazur approved these changes

2024-03-10 12:10 UTC, WojciechMazur approved these changes

2024-03-10 12:11 UTC, merged